CREATE TABLE IF NOT EXISTS `otus_titanic_passengers` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,

    `PASSENGER_EXTERNAL_ID` INT UNSIGNED NOT NULL COMMENT 'PassengerId из CSV',
    `FULL_NAME` VARCHAR(255) NOT NULL COMMENT 'Имя пассажира',
    `SEX` VARCHAR(20) NOT NULL COMMENT 'Пол',
    `AGE` DECIMAL(5,2) NULL COMMENT 'Возраст',
    `SIBSP` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Супруги / братья / сёстры',
    `PARCH` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Родители / дети',
    `FARE` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'Стоимость билета',
    `SURVIVED` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 = погиб, 1 = выжил',

    `TICKET_ID` INT UNSIGNED NOT NULL COMMENT 'Связь с таблицей билетов',
    `PCLASS_ELEMENT_ID` INT UNSIGNED NOT NULL COMMENT 'Связь с инфоблоком классов',
    `EMBARKED_ELEMENT_ID` INT UNSIGNED NULL COMMENT 'Связь с инфоблоком портов',
    `CABIN_DECK_ELEMENT_ID` INT UNSIGNED NULL COMMENT 'Связь с инфоблоком палуб',

    `CABIN_RAW` VARCHAR(255) NULL COMMENT 'Исходная строка Cabin из CSV',

    PRIMARY KEY (`ID`),

    UNIQUE KEY `UX_PASSENGER_EXTERNAL_ID` (`PASSENGER_EXTERNAL_ID`),

    KEY `IX_TICKET_ID` (`TICKET_ID`),
    KEY `IX_PCLASS_ELEMENT_ID` (`PCLASS_ELEMENT_ID`),
    KEY `IX_EMBARKED_ELEMENT_ID` (`EMBARKED_ELEMENT_ID`),
    KEY `IX_CABIN_DECK_ELEMENT_ID` (`CABIN_DECK_ELEMENT_ID`),
    KEY `IX_SURVIVED` (`SURVIVED`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;